version = 1

test_patterns = [
  "tests/**/*",
  "tests/*",
  "test*.py",
  "tests.py", "test_*.py","*_tests.py"
]

exclude_patterns = [".*"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"
